/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#a88f6d',
        'on-surface-variant': '#434843',
        'on-error': '#ffffff',
        'inverse-surface': '#323129',
        'primary-fixed': '#fbdeb8',
        'surface-dim': '#dedace',
        'on-secondary-container': '#556d00',
        'tertiary-fixed': '#d1e4ff',
        'on-tertiary-fixed': '#001d36',
        'tertiary-container': '#002d50',
        'secondary-fixed-dim': '#abd61c',
        'on-background': '#1d1c15',
        'primary-fixed-dim': '#dec29d',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed': '#c6f33e',
        'on-primary-fixed-variant': '#574427',
        secondary: '#506600',
        'on-tertiary-fixed-variant': '#1a4974',
        'on-primary-fixed': '#271903',
        'on-tertiary-container': '#6d96c6',
        background: '#fdf9ed',
        primary: '#221401',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e6e2d6',
        'surface-container': '#f2eee2',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#f5f1e4',
        'surface-tint': '#705b3d',
        'on-secondary-fixed-variant': '#3b4d00',
        'surface-variant': '#e6e2d6',
        'surface-container-high': '#ece8dc',
        'on-surface': '#1d1c15',
        'surface-bright': '#fdf9ed',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        tertiary: '#00182f',
        'inverse-primary': '#dec29d',
        'primary-container': '#39290f',
        surface: '#fdf9ed',
        outline: '#737973',
        'on-secondary-fixed': '#161f00',
        'tertiary-fixed-dim': '#a0cafc',
        'outline-variant': '#c3c8c1',
        'surface-container-low': '#f8f3e7',
        'on-error-container': '#93000a',
        'secondary-container': '#c6f33e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max': '1280px',
        'section-gap': '120px',
        unit: '8px',
        'margin-page': '64px',
        gutter: '24px',
      },
      fontFamily: {
        'label-caps': ['Manrope'],
        'data-mono': ['Manrope'],
        h1: ['Newsreader'],
        'body-lg': ['Manrope'],
        h3: ['Newsreader'],
        'body-md': ['Manrope'],
        h2: ['Newsreader'],
        serif: ['Newsreader', 'Georgia', 'serif'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'data-mono': ['14px', { lineHeight: '1', fontWeight: '600' }],
        h1: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        h3: ['24px', { lineHeight: '1.3', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        h2: ['36px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '500' }],
      },
    },
  },
};
