module.exports = {
  darkMode: "class",
  content: ["./index.html"],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#a88f6d",
        "on-surface-variant": "#434843",
        "inverse-surface": "#323129",
        "primary-fixed": "#fbdeb8",
        "surface-dim": "#dedace",
        "on-secondary-container": "#556d00",
        "on-background": "#1d1c15",
        "primary-fixed-dim": "#dec29d",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#c6f33e",
        "on-primary-fixed": "#271903",
        "on-tertiary-container": "#6d96c6",
        background: "#fdf9ed",
        primary: "#221401",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e6e2d6",
        "surface-container": "#f2eee2",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f5f1e4",
        "surface-tint": "#705b3d",
        "on-secondary-fixed-variant": "#3b4d00",
        "surface-variant": "#e6e2d6",
        "surface-container-high": "#ece8dc",
        "on-surface": "#1d1c15",
        "surface-bright": "#fdf9ed",
        error: "#ba1a1a",
        tertiary: "#00182f",
        "inverse-primary": "#dec29d",
        "primary-container": "#39290f",
        surface: "#fdf9ed",
        outline: "#737973",
        "on-secondary-fixed": "#161f00",
        "outline-variant": "#c3c8c1",
        "surface-container-low": "#f8f3e7",
        "on-error-container": "#93000a",
        secondary: "#506600",
        "secondary-container": "#c6f33e",
      },
      borderRadius: { DEFAULT: "0.125rem", lg: "0.25rem", xl: "0.5rem", full: "0.75rem" },
      fontFamily: {
        "label-caps": ["Manrope"],
        "data-mono": ["Manrope"],
        h1: ["Newsreader"],
        "body-lg": ["Manrope"],
        h3: ["Newsreader"],
        "body-md": ["Manrope"],
        h2: ["Newsreader"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        "data-mono": ["14px", { lineHeight: "1", fontWeight: "600" }],
        h1: ["56px", { lineHeight: "1.05", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        h3: ["24px", { lineHeight: "1.3", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        h2: ["40px", { lineHeight: "1.15", letterSpacing: "-0.02em", fontWeight: "500" }],
      }
    }
  },
  plugins: []
}